# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ep/v1/conversation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ep/v1/conversation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65p/v1/conversation.proto\x12\x05\x65p.v1\"I\n\nAudioChunk\x12\x10\n\x08pcm_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x04\"E\n\x0fTranscriptEvent\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"#\n\x0cStartRequest\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\"G\n\rStartResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61i_text\x18\x02 \x01(\t\x12\x11\n\taudio_wav\x18\x03 \x01(\x0c\"4\n\x0bTurnRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\taudio_wav\x18\x02 \x01(\x0c\"F\n\x0cTurnResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x0f\n\x07\x61i_text\x18\x02 \x01(\t\x12\x11\n\taudio_wav\x18\x03 \x01(\x0c\"\x0f\n\rHealthRequest\"N\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x1a\n\x12provider_connected\x18\x03 \x01(\x08\x32\x83\x02\n\x13\x43onversationService\x12:\n\rStartScenario\x12\x13.ep.v1.StartRequest\x1a\x14.ep.v1.StartResponse\x12;\n\x10\x43onversationTurn\x12\x12.ep.v1.TurnRequest\x1a\x13.ep.v1.TurnResponse\x12<\n\x0bStreamAudio\x12\x11.ep.v1.AudioChunk\x1a\x16.ep.v1.TranscriptEvent(\x01\x30\x01\x12\x35\n\x06Health\x12\x14.ep.v1.HealthRequest\x1a\x15.ep.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ep.v1.conversation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=35
  _globals['_AUDIOCHUNK']._serialized_end=108
  _globals['_TRANSCRIPTEVENT']._serialized_start=110
  _globals['_TRANSCRIPTEVENT']._serialized_end=179
  _globals['_STARTREQUEST']._serialized_start=181
  _globals['_STARTREQUEST']._serialized_end=216
  _globals['_STARTRESPONSE']._serialized_start=218
  _globals['_STARTRESPONSE']._serialized_end=289
  _globals['_TURNREQUEST']._serialized_start=291
  _globals['_TURNREQUEST']._serialized_end=343
  _globals['_TURNRESPONSE']._serialized_start=345
  _globals['_TURNRESPONSE']._serialized_end=415
  _globals['_HEALTHREQUEST']._serialized_start=417
  _globals['_HEALTHREQUEST']._serialized_end=432
  _globals['_HEALTHRESPONSE']._serialized_start=434
  _globals['_HEALTHRESPONSE']._serialized_end=512
  _globals['_CONVERSATIONSERVICE']._serialized_start=515
  _globals['_CONVERSATIONSERVICE']._serialized_end=774
# @@protoc_insertion_point(module_scope)
