# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ep.v1 import conversation_pb2 as ep_dot_v1_dot_conversation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ep/v1/conversation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConversationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartScenario = channel.unary_unary(
                '/ep.v1.ConversationService/StartScenario',
                request_serializer=ep_dot_v1_dot_conversation__pb2.StartRequest.SerializeToString,
                response_deserializer=ep_dot_v1_dot_conversation__pb2.StartResponse.FromString,
                _registered_method=True)
        self.ConversationTurn = channel.unary_unary(
                '/ep.v1.ConversationService/ConversationTurn',
                request_serializer=ep_dot_v1_dot_conversation__pb2.TurnRequest.SerializeToString,
                response_deserializer=ep_dot_v1_dot_conversation__pb2.TurnResponse.FromString,
                _registered_method=True)
        self.StreamAudio = channel.stream_stream(
                '/ep.v1.ConversationService/StreamAudio',
                request_serializer=ep_dot_v1_dot_conversation__pb2.AudioChunk.SerializeToString,
                response_deserializer=ep_dot_v1_dot_conversation__pb2.TranscriptEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ep.v1.ConversationService/Health',
                request_serializer=ep_dot_v1_dot_conversation__pb2.HealthRequest.SerializeToString,
                response_deserializer=ep_dot_v1_dot_conversation__pb2.HealthResponse.FromString,
                _registered_method=True)


class ConversationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartScenario(self, request, context):
        """Start a new scenario and receive the AI opening.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConversationTurn(self, request, context):
        """Process one turn: student audio in -> AI response out.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request_iterator, context):
        """Real-time streaming: bidirectional audio <-> transcript stream.
        Rust (client) streams AudioChunk up;
        Python (server) streams TranscriptEvent down.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScenario,
                    request_deserializer=ep_dot_v1_dot_conversation__pb2.StartRequest.FromString,
                    response_serializer=ep_dot_v1_dot_conversation__pb2.StartResponse.SerializeToString,
            ),
            'ConversationTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.ConversationTurn,
                    request_deserializer=ep_dot_v1_dot_conversation__pb2.TurnRequest.FromString,
                    response_serializer=ep_dot_v1_dot_conversation__pb2.TurnResponse.SerializeToString,
            ),
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=ep_dot_v1_dot_conversation__pb2.AudioChunk.FromString,
                    response_serializer=ep_dot_v1_dot_conversation__pb2.TranscriptEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ep_dot_v1_dot_conversation__pb2.HealthRequest.FromString,
                    response_serializer=ep_dot_v1_dot_conversation__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ep.v1.ConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ep.v1.ConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ep.v1.ConversationService/StartScenario',
            ep_dot_v1_dot_conversation__pb2.StartRequest.SerializeToString,
            ep_dot_v1_dot_conversation__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConversationTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ep.v1.ConversationService/ConversationTurn',
            ep_dot_v1_dot_conversation__pb2.TurnRequest.SerializeToString,
            ep_dot_v1_dot_conversation__pb2.TurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ep.v1.ConversationService/StreamAudio',
            ep_dot_v1_dot_conversation__pb2.AudioChunk.SerializeToString,
            ep_dot_v1_dot_conversation__pb2.TranscriptEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ep.v1.ConversationService/Health',
            ep_dot_v1_dot_conversation__pb2.HealthRequest.SerializeToString,
            ep_dot_v1_dot_conversation__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
