[package]
name = "ep-volcengine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ep-core = { path = "../ep-core" }
tokio = { workspace = true }
futures = { workspace = true }
tokio-tungstenite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
http = { workspace = true }
