[package]
name = "ep-app"
version.workspace = true
edition = "2021"
authors.workspace = true
license.workspace = true

[[bin]]
name = "english-partner"
path = "src/main.rs"

[dependencies]
ep-core = { path = "../ep-core" }
ep-audio = { path = "../ep-audio" }
ep-volcengine = { path = "../ep-volcengine" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rustls = "0.23.39"
